"""M1-01 initial business schema

Revision ID: 18e3af0d1942
Revises:
Create Date: 2026-09-18 19:44:35.859202

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18e3af0d1942"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("parent_operation_id", sa.String(length=128), nullable=True),
        sa.Column("scope", sa.String(length=300), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("last_event_seq", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_operation_id"],
            ["operation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "idempotency_key"),
    )
    op.create_table(
        "profile",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "claim",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("profile_id", sa.String(length=128), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_block_ids", sa.JSON(), nullable=False),
        sa.Column("source_quotes", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("supersedes_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["claim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("profile_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("filename_display", sa.String(length=300), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("extract_status", sa.String(length=24), nullable=False),
        sa.Column("index_status", sa.String(length=16), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operation_event",
        sa.Column("operation_id", sa.String(length=128), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operation.id"],
        ),
        sa.PrimaryKeyConstraint("operation_id", "seq"),
    )
    with op.batch_alter_table("operation_event", schema=None) as batch_op:
        batch_op.create_index(
            "ix_operation_event_op_seq", ["operation_id", "seq"], unique=True
        )

    op.create_table(
        "profile_snapshot",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("profile_id", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("confirmed_claim_ids", sa.JSON(), nullable=False),
        sa.Column("display_fields", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "revision"),
    )
    op.create_table(
        "interview",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("profile_snapshot_id", sa.String(length=128), nullable=False),
        sa.Column("jd_snapshot", sa.JSON(), nullable=False),
        sa.Column("seed_bank_version", sa.String(length=32), nullable=False),
        sa.Column("rubric_version", sa.String(length=32), nullable=False),
        sa.Column("prompt_versions", sa.JSON(), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("model_fingerprint", sa.String(length=200), nullable=False),
        sa.Column("sdk_version", sa.String(length=32), nullable=False),
        sa.Column("run_mode", sa.String(length=16), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("root_plan", sa.JSON(), nullable=False),
        sa.Column("current_question_id", sa.String(length=128), nullable=True),
        sa.Column("active_operation_id", sa.String(length=128), nullable=True),
        sa.Column("stop_requested", sa.Boolean(), nullable=False),
        sa.Column("report_id", sa.String(length=128), nullable=True),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_snapshot_id"],
            ["profile_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_block",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("block_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "page_number", "block_index"),
    )
    op.create_table(
        "assessment",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("interview_id", sa.String(length=128), nullable=False),
        sa.Column("root_question_id", sa.String(length=128), nullable=False),
        sa.Column("criterion_results", sa.JSON(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("coverage", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interview.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("interview_id", sa.String(length=128), nullable=False),
        sa.Column("root_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("seed_id", sa.String(length=128), nullable=False),
        sa.Column("wording", sa.Text(), nullable=False),
        sa.Column("basis", sa.JSON(), nullable=False),
        sa.Column("rubric_snapshot", sa.JSON(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interview.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("interview_id", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("completion", sa.String(length=16), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column("coverage", sa.JSON(), nullable=False),
        sa.Column("root_assessments", sa.JSON(), nullable=False),
        sa.Column("improved_answers", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("run_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interview.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answer",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("question_id", sa.String(length=128), nullable=False),
        sa.Column("interview_id", sa.String(length=128), nullable=False),
        sa.Column("client_turn_id", sa.String(length=128), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("evaluation_status", sa.String(length=16), nullable=False),
        sa.Column("assistance", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interview.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interview_id", "client_turn_id"),
        sa.UniqueConstraint("question_id"),
    )
    op.create_table(
        "observation",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("answer_id", sa.String(length=128), nullable=False),
        sa.Column("question_id", sa.String(length=128), nullable=False),
        sa.Column("root_question_id", sa.String(length=128), nullable=False),
        sa.Column("relevance", sa.String(length=16), nullable=False),
        sa.Column("knowledge_status", sa.String(length=24), nullable=False),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.Column("clarification_needed", sa.Boolean(), nullable=False),
        sa.Column("validation_flags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "decision",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("observation_id", sa.String(length=128), nullable=True),
        sa.Column("root_question_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=48), nullable=False),
        sa.Column("reason_summary", sa.Text(), nullable=False),
        sa.Column("target", sa.JSON(), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("decision")
    op.drop_table("observation")
    op.drop_table("answer")
    op.drop_table("report")
    op.drop_table("question")
    op.drop_table("assessment")
    op.drop_table("source_block")
    op.drop_table("interview")
    op.drop_table("profile_snapshot")
    with op.batch_alter_table("operation_event", schema=None) as batch_op:
        batch_op.drop_index("ix_operation_event_op_seq")

    op.drop_table("operation_event")
    op.drop_table("document")
    op.drop_table("claim")
    op.drop_table("profile")
    op.drop_table("operation")
    # ### end Alembic commands ###
